apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  namespace: ecommerceapp
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: orderservice
          image: ghcr.io/jakubkopecky-dev/orderservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__PublicKey
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__PublicKey
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: ConnectionStrings__DefaultConnection

            - name: MessageBroker__Transport
              value: "AzureServiceBus"
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: AzureServiceBus__ConnectionString
            - name: AzureServiceBus__QueueName
              value: "order-queue"

            - name: DeliveryService__GrpcAddress
              value: "http://deliveryservice:8081"
            - name: PaymentService__GrpcAddress
              value: "http://paymentservice:8081"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
  namespace: ecommerceapp
  labels:
    app: orderservice
spec:
  selector:
    app: orderservice
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
