apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: ecommerceapp
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: paymentservice
          image: ghcr.io/jakubkopecky-dev/paymentservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"

            - name: EnableSwagger
              value: "true"

            - name: Jwt__PublicKey
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__PublicKey
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Issuer
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Jwt__Audience

            - name: MessageBroker__Transport
              value: "AzureServiceBus"
            - name: AzureServiceBus__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: AzureServiceBus__ConnectionString

            - name: Stripe__SecretKey
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Stripe__SecretKey
            - name: Stripe__WebHookSecret
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secrets
                  key: Stripe__WebHookSecret
            - name: Stripe__SuccessUrl
              value: "https://ecommerce.9.163.223.240.nip.io/payment/api/Payment/success"
            - name: Stripe__CancelUrl
              value: "https://ecommerce.9.163.223.240.nip.io/payment/api/Payment/cancel"
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: ecommerceapp
  labels:
    app: paymentservice
spec:
  selector:
    app: paymentservice
  ports:
    - name: rest
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
